# Include all new generators here
set(GENERATORS_SOURCE_FILES generator_cutter.cpp)

# Set RPATH for the shared libraries in this directory
set(CMAKE_INSTALL_RPATH "${INSTALL_PATH}/bin/lib/generator_runner/generators")
set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)

# Compile each generator as a shared object
foreach(src_file ${GENERATORS_SOURCE_FILES})
  get_filename_component(src_name ${src_file} NAME_WE)
  add_library(${src_name} MODULE ${src_file})
  target_link_libraries(${src_name} PRIVATE
    ${CUSTOM_QDMI_LIBRARY_PATH}/libQDMI.so
    ${CUSTOM_FOMAC_LIBRARY_PATH}/libFoMaC.so
    ${CUSTOM_BACKENDS_LIBRARY_PATH}/libBackends.so)

  set_target_properties(
    ${src_name}
    PROPERTIES
      INSTALL_RPATH
      "${CMAKE_INSTALL_PREFIX}/bin/lib/backends:${CMAKE_INSTALL_PREFIX}/bin/lib/fomac:${CMAKE_INSTALL_PREFIX}/bin/lib/qdmi"
      INSTALL_RPATH_USE_LINK_PATH TRUE)

  # Set include directories for the library
  target_include_directories(${src_name} PRIVATE ${CUSTOM_QDMI_INCLUDE_PATH}
                                                 ${CUSTOM_FOMAC_INCLUDE_PATH}
                                                 ${CUSTOM_BACKENDS_INCLUDE_PATH})

  # Install the shared library
  install(TARGETS ${src_name}
          DESTINATION "${INSTALL_PATH}/bin/lib/generator_runner/generators")

endforeach()
