name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  pre-commit:
    name: Pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pre-commit/action@v4.3.0
        with:
          extra_args: --all-files
